services:
  uberdb:
    container_name: uberdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433" 
  messagebroker:
    container_name: messagebroker
    hostname: uber-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"