services:
  messagebroker:
    container_name: messagebroker
    hostname: uber-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  distributedcache:
    container_name: distributedcache
    image: redis
    ports:
      - "6379:6379"